import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const neueMontreal = localFont({ src: '../fonts/NeueMontreal-Regular.woff2' })

export const metadata: Metadata = {
  title: "Stemps",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={neueMontreal.className}
      >
        {children}
      </body>
    </html>
  );
}
